Resturant_Page/resturant_page/foods/urls.py
from django.contrib import admin
from django.urls import path
from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('menu/', views.showMenu , name='menu'),
    path('create-review', views.createReview , name='create-review'),
    path('food/<str:pk>', views.showFood , name='food'),
    path('', views.showHome , name='home'),

    path('admin-food-create/', views.create_Food , name='admin-food-create'),
    path('admin-food-update/<str:pk>', views.update_Food , name='admin-food-update'),
    path('admin-food-delete/<str:pk>', views.delete_Food , name='admin-food-delete'),
    path('admin-page/', views.read_Food , name='admin-page'),

    path('admin-ingredient-create/', views.create_Ingredient , name='admin-ingredient-create'),
    path('admin-ingredient-update/<str:pk>', views.update_Ingredient , name='admin-ingredient-update'),
    path('admin-ingredient-delete/<str:pk>', views.delete_Ingredient , name='admin-ingredient-delete'),
    path('admin-ingredient-page/', views.read_Ingredient , name='admin-ingredient-page'),
    
]

Resturant_Page/resturant_page/resturant_page/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('foods/', include('foods.urls')),
    path('users/', include('users.urls')),
    path('orders/', include('orders.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Resturant_Page/resturant_page/foods/models.py
from django.db import models

from django.db import models
import uuid
# Create your models here.

class Ingredient(models.Model):
    name= models.CharField(max_length=300)
    created= models.DateTimeField(auto_now_add=True)
    id=models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
     
    def __str__(self):
        return self.name


class Food(models.Model):
    name= models.CharField(max_length=300)
    ing=models.ManyToManyField(Ingredient,null=True,blank=True)
    price=models.CharField(max_length=20,blank=True, null=True)
    image= models.ImageField(null=True, blank=True,upload_to='food/')
    discount=models.IntegerField(default=0,blank=True, null=True)
    
    created= models.DateTimeField(auto_now_add=True)
    id=models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
     
    def __str__(self):
        return self.name
    
    @property
    def getDiscountPrice(self):
        self.price=int(self.price) - (int(self.price) * self.discount / 100)
        return self.price
        
    @property
    def imageURL(self):
        try:
            img=self.image.url

        except:
            img=''

        return img

    

Resturant_Page/resturant_page/users/models.py
from django.db import models
from django.contrib.auth.models import User
from foods.models import Food
import uuid
# Create your models here.

class Profile(models.Model):
    user=models.OneToOneField(User, on_delete=models.CASCADE)
    username=models.CharField(max_length = 150, blank=True, null=True)
    firstname=models.CharField(max_length=200,blank=True, null=True)
    lastname=models.CharField(max_length=200, blank=True, null=True)
    address=models.TextField()
    phone=models.CharField(max_length = 11, blank=True, null=True)
    created= models.DateTimeField(auto_now_add=True)
    id=models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return self.username
    

class Review(models.Model):
    owner=models.ForeignKey(Profile, on_delete=models.CASCADE)
    food=models.ForeignKey(Food,on_delete=models.CASCADE)
    comment=models.TextField()
    created= models.DateTimeField(auto_now_add=True)
    id=models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return str(self.created)

    

    
    
    

Resturant_Page/resturant_page/foods/forms.py
from django.forms import ModelForm
from django.contrib.auth.models import User
from .models import Food, Ingredient



class FoodForm(ModelForm):
    class Meta:
        model=Food
        fields='__all__'

    def  __init__(self,*args,**kwargs):
      

        super(FoodForm, self).__init__(*args,**kwargs)
        for key, value in self.fields.items():
            value.widget.attrs.update({'class':'form-control','type':'text'})

            
class IngredientForm(ModelForm):
    class Meta:
        model=Ingredient
        fields='__all__'

    def  __init__(self,*args,**kwargs):
      

        super(IngredientForm, self).__init__(*args,**kwargs)
        for key, value in self.fields.items():
            value.widget.attrs.update({'class':'form-control','type':'text'})            

Resturant_Page/resturant_page/foods/views.py
from django.shortcuts import render, redirect
from .models import Food ,Ingredient
from users.models import Profile,Review
from .forms import FoodForm,IngredientForm
# Create your views here.
from django.contrib.auth.decorators import login_required
from django.contrib import messages


def showHome(request):
    foods=Food.objects.all()
    context={'foods':foods}
    return render(request,'foods/home.html', context)

def showMenu(request):
    foods=Food.objects.all()
    context={'foods':foods}
    return render(request,'foods/menu.html', context)

def showFood(request,pk):
    food=Food.objects.get(id=pk)
    
            
    context={'food':food}
    return render(request,'foods/food.html', context)

@login_required(login_url='login')
def createReview(request):
    user=request.user
    profile=Profile.objects.get(user=user)

    if request.method == 'POST':
        comment=request.POST['comment']
        id_food=request.POST['food']
        food=Food.objects.get(id=id_food)

       
        if comment:
            review=Review.objects.create(owner=profile,comment=comment,food=food)
            return redirect('food',food.id)
    

#########################################################
#########################################################
############ admin ######################################
@login_required(login_url='login')
def read_Food(request):
    foods=Food.objects.all()
    context={'foods':foods}
    return render(request,'foods/admin_page.html',context)

@login_required(login_url='login')
def update_Food(request,pk):
    page='update'
    user=request.user
    food=Food.objects.get(id=pk)
    form=FoodForm(instance=food)
    if user.is_staff:
        if request.method == 'POST':
            form=FoodForm(request.POST,request.FILES,instance=food)
            if form.is_valid():
                form.save()
                return redirect('admin-page')
            else:
                pass
    context={'page':page,'form':form,'food':food }
    return render(request,'foods/form_page.html',context)

@login_required(login_url='login')
def create_Food(request):
    page='create'
    user=request.user
    form=FoodForm()
    if user.is_staff:
        if request.method == 'POST':
            form=FoodForm(request.POST,request.FILES)
            if form.is_valid:
                form.save()
                return redirect('admin-page')
            else:
                pass


    context={'page':page,'form':form}
    return render(request,'foods/form_page.html',context)

@login_required(login_url='login')
def delete_Food(request,pk):
    food=Food.objects.get(id=pk)
    food.delete()
    
    return redirect('admin-page')

@login_required(login_url='login')
def read_Ingredient(request):
    ingredients=Ingredient.objects.all()
    context={'ingredients':ingredients}
    return render(request,'foods/admin_ingredient_page.html',context)

@login_required(login_url='login')
def update_Ingredient(request,pk):
    page='update_ingredient'
    user=request.user
    ingredient=Ingredient.objects.get(id=pk)
    form=IngredientForm(instance=ingredient)
    if user.is_staff:
        if request.method == 'POST':
            form=IngredientForm(request.POST,request.FILES,instance=ingredient)
            if form.is_valid():
                form.save()
                return redirect('admin-ingredient-page')
            else:
                pass
    context={'page':page,'form':form,'ingredient':ingredient}
    return render(request,'foods/form_page.html',context)

@login_required(login_url='login')
def create_Ingredient(request):
    page='create_ingredient'
    user=request.user
    form=IngredientForm()
    if user.is_staff:
        if request.method == 'POST':
            form=IngredientForm(request.POST,request.FILES)
            if form.is_valid():
                form.save()
                return redirect('admin-ingredient-page')
            else:
                pass


    context={'page':page,'form':form}
    return render(request,'foods/form_page.html',context)
@login_required(login_url='login')
def delete_Ingredient(request,pk):
    ingredient=Ingredient.objects.get(id=pk)
    ingredient.delete()
    
    return redirect('admin-ingredient-page')

Resturant_Page/resturant_page/foods/templates/foods/admin_ingredient_page.html
{% extends 'main.html' %}

{% block content %}
<section id="price">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="block">
                    <h1 class="heading wow fadeInUp" data-wow-duration="300ms" data-wow-delay="300ms">our
                        <span>MENU</span> the <span>PRICE</span></h1>
                   
                    <div class="pricing-list">
                        <div class="title">
                            <h3>Featured <span>on the week</span></h3>
                        </div>
                        <ul>
                            {% for ingredient in ingredients %}
                            <li class="wow fadeInUp" data-wow-duration="300ms" data-wow-delay="300ms">
                                <div class="item">
                                    <div class="item-title">
                                        <h2>{{ingredient.name}}</h2>
                                        <div class="border-bottom" style="    width: 90%;"></div>
                                        <a href="{% url 'admin-ingredient-update' ingredient.id %}" style="float: right;
                                        background-color: #FF5333;
                                        padding-left: 7px;
                                        padding-right: 7px;
                                        color: white;
                                        font-size: 18px;
                                        border-radius: 25px;"> update</a>
                                        <a href="{% url 'admin-ingredient-delete' ingredient.id %}" style="float: right;
                                        background-color: #FF5333;
                                        padding-left: 7px;
                                        padding-right: 7px;
                                        color: white;
                                        font-size: 18px;
                                        border-radius: 25px;"> delete</a>
                                        
                                        
                                    </div>
                                   
                                </div>
                            </li>
                            {% endfor %}
                            
                            
                        </ul>
                        <a class="btn btn-default pull-right wow bounceIn" data-wow-duration="500ms" data-wow-delay="1200ms"
                            href="{% url 'admin-ingredient-create'%}" role="button">Create New Item</a>
                    </div>
                </div>
            </div><!-- .col-md-12 close -->
        </div><!-- .row close -->
    </div><!-- .containe close -->
</section><!-- #price close -->
{% endblock content %}

Resturant_Page/resturant_page/foods/templates/foods/admin_page.html
{% extends 'main.html' %}

{% block content %}
<section id="price">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="block">
                    <h1 class="heading wow fadeInUp" data-wow-duration="300ms" data-wow-delay="300ms">our
                        <span>MENU</span> the <span>PRICE</span></h1>
                   
                    <div class="pricing-list">
                        <div class="title">
                            <h3>Featured <span>on the week</span></h3>
                        </div>
                        <ul>
                            {% for food in foods %}
                            <li class="wow fadeInUp" data-wow-duration="300ms" data-wow-delay="300ms">
                                <div class="item">
                                    <div class="item-title">
                                        <h2>{{food.name}}</h2>
                                        <div class="border-bottom" style="    width: 90%;"></div>
                                        <a href="{% url 'admin-food-update' food.id %}" style="float: right;
                                        background-color: #FF5333;
                                        padding-left: 7px;
                                        padding-right: 7px;
                                        color: white;
                                        font-size: 18px;
                                        border-radius: 25px;"> update</a>
                                        <a href="{% url 'admin-food-delete' food.id %}" style="float: right;
                                        background-color: #FF5333;
                                        padding-left: 7px;
                                        padding-right: 7px;
                                        color: white;
                                        font-size: 18px;
                                        border-radius: 25px;"> delete</a>
                                        <span style="    font-size: 18px;
                                        margin-right: 7px;">$ {{food.price}}</span>
                                        
                                    </div>
                                    <p>. {% for ingredient in food.ing.all %}
                                      <span>{{ingredient}}</span> .
                                        {% endfor %}
                                    </p>
                                </div>
                            </li>
                            {% endfor %}
                            
                            
                        </ul>
                        <a class="btn btn-default pull-right wow bounceIn" data-wow-duration="500ms" data-wow-delay="1200ms"
                            href="{% url 'admin-food-create' %}" role="button">Create New Item</a>
                    </div>
                </div>
            </div><!-- .col-md-12 close -->
        </div><!-- .row close -->
    </div><!-- .containe close -->
</section><!-- #price close -->
{% endblock content %}

Resturant_Page/resturant_page/foods/templates/foods/food.html
{% extends 'main.html' %}
{% block content%}

<section id="price">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="block">
                
                    <div class="pricing-list">
                        <div class="title">
                            <h3>Featured <span>on the week</span></h3>
                        </div>
                        <ul>
                           
                            <li class="wow fadeInUp" data-wow-duration="300ms" data-wow-delay="300ms">
                                <div class="item">
                                    <div class="item-title">
                                        <ul>
                                            <li class="wow fadeInUp">
                                                <img src="{{food.imageURL}}" height="250" width="250">
                                            </li>
                                            <li class="wow fadeInUp"><span style="font-size: 23px;">{{food.name}}</span></li>
                                            <li class="wow fadeInUp"> 
                                                <ul>
                                                    <li><span style="font-size: 23px;">ingredients:</span></li>
                                                    {% for ingredient in food.ing.all %}
                                                    <li><span style="font-size: 23px;">ingredients:{{ingredient}} -</span> </li>
                                                    {% endfor %}
                                                </ul>
                                                
                                                  </li>

                                            <li class="wow fadeInUp"><span style="font-size: 23px;"> price :$ {{food.price}}</span></li>
                                            {% if food.discount != 0 %}
                                            <li class="wow fadeInUp"><span style="font-size: 23px;"> price with {{food.discount}}% discount :$ {{food.getDiscountPrice}}</span></li>
                                            {% endif%}
                                            <li class="wow fadeInUp"><a href="{% url 'create-order' food.id %}" class="btn btn-default pull-right wow bounceIn" data-wow-duration="500ms" data-wow-delay="1200ms" role="button"> Order</a></li>
                                        </ul>
                                        
                                        
                                        
                                       
            
                                        
                                        
                                    </div>
                                    
                                </div>
                            </li>
                            
                            
                            
                        </ul>
                        
                    </div>
                </div>
            </div><!-- .col-md-12 close -->
        </div><!-- .row close -->
    </div><!-- .containe close -->
</section><!-- #price close -->




<section id="contact-us">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="block">
                    <h1 class="heading wow fadeInUp" data-wow-duration="500ms" data-wow-delay="300ms">
                        <span>You can add your comment here</span></h1>
                    <h3 class="title wow fadeInLeft" data-wow-duration="500ms" data-wow-delay="300ms"> 
                        </h3>
                    <form action="{% url 'create-review' %}" method="POST">
                        {% csrf_token %}

                        <div class="form-group wow fadeInDown" data-wow-duration="500ms" data-wow-delay="600ms">
                            <input type="text" name="comment" class="form-control" id="exampleInputEmail1"
                                placeholder="Write your comment here...">
                             <input type="hidden" name="food" value="{{food.id}}">
                        </div>
                        
                        <button type="submit" class="btn btn-default wow bounceIn" data-wow-duration="500ms" data-wow-delay="1300ms" 
                       >Submit</button>
                    </form>
                     
                </div>
               
            </div>
        </div>
    </div>
</section>




<section id="price">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="block">
                    
                    <div class="pricing-list">
                        <div class="title">
                            <h3>Customer's <span> Comments </span></h3>
                        </div>
                        <ul>
                            {% for review in food.review_set.all %}
                            <li class="wow fadeInUp" data-wow-duration="300ms" data-wow-delay="300ms">
                                <div class="item">
                                    <div class="item-title">
                                        <h2>{{review.owner.username}}</h2>
                                        
                                        <span style="    font-size: 18px;
                                        margin-right: 7px;">{{review.comment}}</span>
                                        
                                    </div>
                                    
                                </div>
                            </li>
                            {% endfor %}
                            
                            
                        </ul>
                       
                    </div>
                </div>
            </div><!-- .col-md-12 close -->
        </div><!-- .row close -->
    </div><!-- .containe close -->
</section><!-- #price close -->


{% endblock content%}

Resturant_Page/resturant_page/foods/templates/foods/form_page.html
{% extends 'main.html' %}
{% block content %}


{% if page == 'update_ingredient' %}


<!--- update user ---->

<section id="contact-us">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="block">
                    <h1 class="heading wow fadeInUp" data-wow-duration="500ms" data-wow-delay="300ms">
                        <span>Update Ingredient Item</span></h1>
                    <h3 class="title wow fadeInLeft" data-wow-duration="500ms" data-wow-delay="300ms"> 
                        </h3>
                    <form action="{% url 'admin-ingredient-update' ingredient.id %}" method="POST">
                        {% csrf_token %}

                        {% for field in form %}
                        <label for="">{{field.label}}</label>
                        {{field}}

                   
                        {% endfor %}
                        <button type="submit" class="btn btn-default wow bounceIn" data-wow-duration="500ms" data-wow-delay="1300ms" 
                       >submit</button>
                    </form>
                     
                </div>
               
            </div>
        </div>
    </div>
</section>

{% elif page == 'create_ingredient' %}


<!--- update user ---->

<section id="contact-us">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="block">
                    <h1 class="heading wow fadeInUp" data-wow-duration="500ms" data-wow-delay="300ms">
                        <span>Create Ingrediernt Item</span></h1>
                    <h3 class="title wow fadeInLeft" data-wow-duration="500ms" data-wow-delay="300ms"> 
                        </h3>
                    <form action="{% url 'admin-ingredient-create' %}" method="POST">
                        {% csrf_token %}

                        {% for field in form %}
                        <label for="">{{field.label}}</label>
                        {{field}}

                   
                        {% endfor %}
                        <button type="submit" class="btn btn-default wow bounceIn" data-wow-duration="500ms" data-wow-delay="1300ms" 
                       >submit</button>
                    </form>
                     
                </div>
               
            </div>
        </div>
    </div>
</section>

{% elif page == 'update_food' %}


<!--- update user ---->

<section id="contact-us">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="block">
                    <h1 class="heading wow fadeInUp" data-wow-duration="500ms" data-wow-delay="300ms">
                        <span>Update Food Item</span></h1>
                    <h3 class="title wow fadeInLeft" data-wow-duration="500ms" data-wow-delay="300ms"> 
                        </h3>
                    <form action="{% url 'admin-food-update' food.id  %}" method="POST">
                        {% csrf_token %}

                        {% for field in form %}
                        <label for="">{{field.label}}</label>
                        {{field}}

                   
                        {% endfor %}
                        <button type="submit" class="btn btn-default wow bounceIn" data-wow-duration="500ms" data-wow-delay="1300ms">submit</button>
                    </form>
                     
                </div>
               
            </div>
        </div>
    </div>
</section>

{% else %} 

<!--- registeration ---->
<section id="contact-us">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="block">
                    <h1 class="heading wow fadeInUp" data-wow-duration="500ms" data-wow-delay="300ms">
                        <span>Create Food Item</span></h1>
                    <h3 class="title wow fadeInLeft" data-wow-duration="500ms" data-wow-delay="300ms"> 
                        </h3>
                    <form action="{% url 'admin-food-create' %}" method="POST">
                        {% csrf_token %}

                        {% for field in form %}
                        <label for="">{{field.label}}</label>
                        {{field}}

                       
                        {% endfor %}
                        <button type="submit" class="btn btn-default wow bounceIn" data-wow-duration="500ms" data-wow-delay="1300ms" 
                       >submit</button>
                    </form>
                     
                </div>
                 
            </div><!-- .col-md-12 close -->
        </div><!-- .row close -->
    </div><!-- .container close -->
</section><!-- #contact-us close -->
{% endif%}

{% endblock content %}

Resturant_Page/resturant_page/foods/templates/foods/home.html
{% extends 'main.html' %}
{% load static %}
{% block content%}

<section id="slider">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="block wow fadeInUp" data-wow-duration="500ms" data-wow-delay="300ms">
                    <div class="title">
                        <h3>Featured <span>Works</span></h3>
                    </div>
                    <div id="owl-example" class="owl-carousel">
                        {% for food in foods %}
                        <div class="owl-item" style="width: 344px;">
                        <div>
                            <a href="{% url 'food' food.id %}"> <img class="img-responsive"  src="{{food.imageURL}}" alt=""></a>
                        </div>
                    </div>
                        {% endfor%}

                       

                    </div>
                </div>
            </div><!-- .col-md-12 close -->
        </div><!-- .row close -->
    </div><!-- .container close -->
</section><!-- slider close -->

<section id="about-us">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="block">
                    <img class="wow fadeInUp" data-wow-duration="300ms" data-wow-delay="400ms" src="{% static 'images/cooker-img.png' %}"
                        alt="cooker-img">
                    <h1 class="heading wow fadeInUp" data-wow-duration="400ms" data-wow-delay="500ms">Your
                        <span>Restaurant’s</span> </br> Website Has To Look <span>Good</span>
                    </h1>
                    <p class="wow fadeInUp" data-wow-duration="300ms" data-wow-delay="600ms">Lorem ipsum dolor sit
                        amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore
                        magna aliqua. Ut enim </br> ad minim veniam, quis nostrud exercitation ullamco laboris nisi
                        ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in </br>voluptate
                        velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat</p>
                </div>
            </div><!-- .col-md-12 close -->
        </div><!-- .row close -->
    </div><!-- .containe close -->
</section><!-- #call-to-action close -->





<section id="blog">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="block">
                    <h1 class="heading">Latest <span>From</span> the <span>Blog</span></h1>
                    <ul>
                        {% for food in foods%}
                        <li class="wow fadeInLeft" data-wow-duration="300ms" data-wow-delay="300ms">
                            <div class="blog-img">
                                <a href="{% url 'food' food.id %}"><img src="{{food.imageURL}}" width="285" height="220" alt="blog-img"></a>
                            </div>
                            <div class="content-right">
                                <h3><a href="{% url 'food' food.id %}">{{food.name}}</a></h3>
                                <p>.{% for ingredient in food.ing.all %}
                                   <span>{{ingredient}}.</span> 
                                    {% endfor%}
                                </p>
                               
                            </div>
                            <a href="{% url 'create-order' food.id %}" class="btn btn-default btn-more-info wow bounceIn" data-wow-duration="500ms" data-wow-delay="1200ms"
                            style="padding: 8px 10px;background: #ff7337;" role="button">Add to Orders</a>
                        </li>
                        {% endfor%}
                        
                       
                       
                       
                      
                    </ul>
                 <!--    <a class="btn btn-default btn-more-info wow bounceIn" data-wow-duration="500ms" data-wow-delay="1200ms"
                        href="#" role="button">More Info</a>-->
                </div>
            </div><!-- .col-md-12 close -->
        </div><!-- .row close -->
    </div><!-- .containe close -->
</section><!-- #blog close -->
{% endblock content%}